// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Reviewed.")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1200:Using directives should be placed correctly", Justification = "Reviewed.")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.GroupType")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.GroupType")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.GroupOfStudents")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.Gym")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "member", Target = "~M:ZRdemoData.Intrefaces.IGenericRepository`1.RemoveRange(System.Collections.Generic.IEnumerable{`0})")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.Gender")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.Gender")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.MemberOfTheTeam")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.Belts")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.Belts")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.Student")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.TypeOfTraining")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.TypeOfTraining")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.Uniform")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.Uniform")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.Training")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.TrainingDay")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "member", Target = "~M:ZRdemoData.Models.ZRdemoContext.#ctor(Microsoft.EntityFrameworkCore.DbContextOptions{ZRdemoData.Models.ZRdemoContext})")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1502:Element should not be on a single line", Justification = "Reviewed.", Scope = "member", Target = "~M:ZRdemoData.Models.ZRdemoContext.#ctor(Microsoft.EntityFrameworkCore.DbContextOptions{ZRdemoData.Models.ZRdemoContext})")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.ZRdemoContext")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Models.Coach")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Repositories.GenericRepository`1")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1309:Field names should not begin with underscore", Justification = "Reviewed.", Scope = "member", Target = "~F:ZRdemoData.Repositories.GenericRepository`1._context")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:ZRdemoData.Repositories.GenericRepository`1._context")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Intrefaces.IGenericRepository`1")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Intrefaces.IStudentRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.>", Scope = "type", Target = "~T:ZRdemoData.Repositories.StudentRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Intrefaces.ICoachRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Intrefaces.IGroupOfStudentsRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Intrefaces.IGymRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Intrefaces.IMemberRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Intrefaces.ITrainingDayRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Intrefaces.ITrainingRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Repositories.CoachRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Repositories.GroupOfStudentsRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Repositories.GymRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Repositories.MemberRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Repositories.TrainingDayRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Repositories.TrainingRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.Intrefaces.IUnitOfWork")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1309:Field names should not begin with underscore", Justification = "Reviewed.", Scope = "member", Target = "~F:ZRdemoData.UnitOfWork.UnitOfWork._context")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Reviewed.", Scope = "type", Target = "~T:ZRdemoData.UnitOfWork.UnitOfWork")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "<Pending>", Scope = "member", Target = "~M:ZRdemoData.Migrations.InitialZRdemo3DB.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
